### ISSUE TITLE
Wrong executable path on CentOS 7.1 (.old)

### ISSUE THREAD

**Issue by clns** [kardianos/osext#10]
I'm on a CentOS Linux release 7.1.1503 (Core) machine and `osext.Executable()` returns `/usr/bin/.myexe.old` instead of `/usr/bin/myexe` after the initial executable gets changed.

I see in [osext_procfs.go](https://github.com/kardianos/osext/blob/8fef92e41e22a70e700a96b29f066cda30ea24ef/osext_procfs.go#L25) that `(deleted)` gets trimmed, but in this case it is not enough.

Do we want to trim `.` and `.old` also?

**Comment by kardianos** [comment]
What is the kernel version there?

**Comment by clns** [comment]
``` sh
$ cat /proc/version 
Linux version 3.10.0-229.4.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC) ) #1 SMP Wed May 13 10:06:09 UTC 2015
```

**Comment by kardianos** [comment]
The problem with any detection, including the current detection, is the modified filename it reports "could" be the real filename.

One workaround for all this is to detect the filename on init so:

```
func init() {
   path, err = executable()
}

func Executable() (string, error) {
     return path, err
}
```

I don't _think_ this would be a semantic change, but I think it would work around all these issues. Thoughts?

**Comment by clns** [comment]
I don't see any problems with this. It is also a proposed solution here: http://stackoverflow.com/questions/28953307/how-to-handle-readlink-of-proc-self-exe-when-executable-is-replaced-during

**Comment by kardianos** [comment]
Okay, it is also consistent with the proposal to add "os.Executable()" to the std lib.
