### ISSUE TITLE
osext/osext_procfs.go should treat dragonfly and FreeBSD the same way

### ISSUE THREAD

**Issue by yurivict** [kardianos/osext#14]
Currently FreeBSD is missing.

**Comment by plouj** [comment]
:+1:

**Comment by kardianos** [comment]
@yurivict @plouj Can you explain why you thought FreeBSD support was missing? It was present in the sysctl file. I failed to check that first.

**Comment by yurivict** [comment]
When I looked, I only saw Dragonfly and not FreeBSD in one place. When something is done for one, it should be done for another too.

**Comment by kardianos** [comment]
I think you are almost correct.
DragonflyBSD doesn't have the syscall that FreeBSD has, it has been removed I think. They both have the same /proc file, true, but BSD don't mandate mounting /proc to the best of my understanding.
