### ISSUE TITLE
Doesn't build on FreeBSD

### ISSUE THREAD

**Issue by calmh** [kardianos/osext#15]
```
jb@syno:~/s/g/k/osext $ git rev-parse HEAD
431e263e413efe4446ede50cec4819b26659fbe7
jb@syno:~/s/g/k/osext $ GOOS=freebsd go install
# github.com/kardianos/osext
./osext_sysctl.go:20: executable redeclared in this block
    previous declaration at ./osext_procfs.go:17
```

**Comment by calmh** [comment]
Given the latest commit I guess the FreeBSD code and build tag should be removed from osext_sysctl?

**Comment by kardianos** [comment]
Aw stink, I'm sorry. Let me first revert.

Was FreeBSD broken as suggested by issue #14 ? Or did someone just forget to read the source code? I suspect /proc is optional on most BSDs, so the syscall would be more reliable when it is an option.

**Comment by kardianos** [comment]
This was fixed in the mentioned fix. I incorrectly assumed it was missing due to #14 being opened without checking. I should have looked, at least tested. Now fixed.
