### ISSUE TITLE
The method for execpath is not so proper

### ISSUE THREAD

**Issue by chiyouhen** [kardianos/osext#16]
In this case:
`bin` dir or any parent dir of `bin` dir is a symlink to other dir, readlink returns an incorrect full path for exec. This is not easy to make user understand. And in some cases, the real path of that link may not in `$PATH` env.

I make a little change in the function `executable` as following:

``` diff
--- osext-master/osext_procfs.go        2015-12-22 23:32:29.000000000 +0800
+++ osext/osext_procfs.go       2016-02-04 16:31:20.000000000 +0800
@@ -10,21 +10,23 @@
        "errors"
        "fmt"
        "os"
+       "os/exec"
        "runtime"
        "strings"
+       "path/filepath"
 )

 func executable() (string, error) {
        switch runtime.GOOS {
        case "linux":
-               const deletedTag = " (deleted)"
-               execpath, err := os.Readlink("/proc/self/exe")
-               if err != nil {
-                       return execpath, err
+               if strings.HasPrefix(os.Args[0], "/") {
+                       return os.Args[0], nil
+               } else if strings.Contains(os.Args[0], "/") {
+                       var cwd, _ = os.Getwd()
+                       return filepath.Join(cwd, os.Args[0]), nil
+               } else {
+                       return exec.LookPath(os.Args[0])
                }
-               execpath = strings.TrimSuffix(execpath, deletedTag)
-               execpath = strings.TrimPrefix(execpath, deletedTag)
-               return execpath, nil
        case "netbsd":
                return os.Readlink("/proc/curproc/exe")
        case "dragonfly":
```

To make code clear to understand, some error processings are ignored in above.

And I dont know what the behavior of bsd or solaris, so I just changed the code of linux. But I think they should be the same.

**Comment by kardianos** [comment]
@chiyouhen Thanks for the report.

However, Executable doesn't use os.Args[0] at all nor does it look at the $PATH environment variable. Executable doesn't guarantee the "real" path, simply "a" path to the executable. I can try out the situation you suggested, but if anything we would just need to check all parent path for symlinks.

The proposed solution is a non-starter.

**Comment by chiyouhen** [comment]
@kardianos , thanks for you answer. I get your point.

I suggest to add another function to provide the 'running path' of current running program. In some cases, the program needs to know the exactly path of running in order to locate the configure file or other files relative to the running dir. You must know some deploy system does not copy or move the whole file to the bin path, they just make a symlink (symlinks to each files, not the whole directory), so the program cannot use relative path to location resources if it cannot get a correct 'running path'.

I think the running path, the path that the system and normal user considered the program in, is more important than the realpath of the file.

Of course, if you don't think the suggestion match the aim of this project, ignore the suggestion, it's ok.

**Comment by kardianos** [comment]
The problem with os.Args[0] is that it is completely user defined and completely arbitrary. It is only set by convention. The design of this package is to expose a per operating system path to the executable to provide a reliable path to the executable binary.

One of the main reasons for this is to provide a completely accurate way to find relative configuration files and other resource. I often use this package to find configuration files that I place relative to my binary.
