### ISSUE TITLE
osext doesn't work on Go 1.6's "go run"

### ISSUE THREAD

**Issue by hachi8833** [kardianos/osext#17]
Hello,
I found that `osext.ExecutableFolder()` returns incorrect path when running "go run" on OSX since Go 1.6:

> fork/exec /private/var/folders/d3/vdcdk3yx5f94ddnpbl0wtxyc0000gn/T/go-build785614328/command-line-arguments/_obj/exe/Electron: no such file or directory
- osext works on "go build" as usual.

I'd be glad if you fix this.

**Comment by xiegeo** [comment]
Which folder do you expect it to return?
See issue #2 

However, "no such file or directory" is a bad error for any path. Can you show the complete code that produced the error?

**Comment by kardianos** [comment]
@hachi8833 That path is correct. "go run" creates a temporary folder and places the executable in that folder before running it. This will _not_ give you the location of your source code, ever.

Try running `go build .` then ./<myapp>. It will output the folder the executable is in.

**Comment by hachi8833** [comment]
Thank you for the checking!
After that the issue has been resolved without any changes...just by rebooting some times.
