### ISSUE TITLE
Does this package work on Mac OS? 

### ISSUE THREAD

**Issue by Bunchhieng** [kardianos/osext#18]
```
folderPath, err := osext.ExecutableFolder()
    if err != nil {
        log.Fatal(err)
    }
    fmt.Println(folderPath)
```

Output:
`/var/folders/j3/0pdflnzn5zx7scbsr24g0fsr0000gn/T/go-build162307922/command-line-arguments/_obj/exe`

or Is there a better way to get a current directory on OSX?

**Comment by kardianos** [comment]
Did you use "go run"? If so, the output looks correct. This package returns the _true_ path of the executable and "go run" uses a temp dir.
