### ISSUE TITLE
document Executable is now in std lib as of go1.8

### ISSUE THREAD

**Issue by bbalet** [kardianos/osext#20]
Hi,

See https://beta.golang.org/pkg/os/#Executable

**Comment by kardianos** [comment]
Thanks, I'm aware. It would be good to add documentation to this project to that effect.

**Comment by kardianos** [comment]
Document that the Executable call is now in "os" in both godoc and README.

**Comment by dmitshur** [comment]
@kardianos, would you recommend using `os.Executable` over `osext.Executable` in all situations where possible (i.e., Go 1.8+), or are there any reasons to stick with `osext` (aside from support for Go 1.7 and older)?

**Comment by kardianos** [comment]
@shurcooL I'd switch to os.Executable.
I've pushed this update so it is ready for go1.8.
