### ISSUE TITLE
intermittent test failures / race conditions? (with go 1.8)

### ISSUE THREAD

**Issue by decathorpe** [kardianos/osext#21]
I'm trying to create a package of this go library for fedora, but the tests fail inconsistently. About 3/12 times the tests fail, and the error looks like a race condition to me (which is supported by the fact that this happens mostly in the slowest build VMs: 2 x aarch64, 1 x ppc64le).

```
+ go test -compiler gc -ldflags '' github.com/kardianos/osext
--- FAIL: TestExecutableDelete (0.00s)
	osext_test.go:135: Child returned "/tmp/go-build761114003/github.com/kardianos/osext/_test/osext.test (deleted)", not the same file as "/tmp/go-build761114003/github.com/kardianos/osext/_test/osext.test"
FAIL
FAIL	github.com/kardianos/osext	0.007s
```

Is there anything I can do about that, or is it a bug?

**Comment by kardianos** [comment]
Oh you are on go1.8. I need to send a fix.

**Comment by mckaygerhard** [comment]
this its realted to go 1.8 version or are a rare condition in the package, i need this solved to for packagin into debian the gogs dependence

**Comment by mckaygerhard** [comment]
this its realted to go 1.8 version or are a rare condition in the package?, i need this solved to for packagin into debian the gogs dependence: https://github.com/MTecknology/gitea-wip/issues/1

**Comment by decathorpe** [comment]
I just checked again, and this issue is still present. Additionally, it is definitely caused by a race condition (either in the code, or in the test itself). Running tests on an idle system, the test always succeeds, but running the test while the system is under heavy CPU load the "TestExecutableDelete" test fails non-deterministically (but more than half of the time).

**Comment by xiegeo** [comment]
@decathorpe What is your current environment? Go version and such.

**Comment by xiegeo** [comment]
Also, you should be using https://golang.org/pkg/os/#Executable now

**Comment by decathorpe** [comment]
$ go version
go version go1.9.5 linux/amd64

**Comment by decathorpe** [comment]
So, usage of github.com/kardianos/osext should be replaced by using the other thing you linked? I'll inform the syncthing devs of that.

**Comment by xiegeo** [comment]
Yes, this library was replaced by a builtin in the standard library. You should used the one in the os library unless you need to support older versions of Go.

**Comment by decathorpe** [comment]
Okay, thanks! Guess this issue can be closed then.

**Comment by dmitshur** [comment]
> I just checked again, and this issue is still present.

But the README says:

> As of go1.8 the Executable function may be found in `os`. The Executable function
in the std lib `os` package is used if available.

Does that mean the issue is also present in `os.Executable` of the standard library?

I’m not seeing any open issues about it at https://goissues.org/os.

**Comment by decathorpe** [comment]
It's possible that this issue is a race condition in the test code itself, not in the actual code of `os.Executable()`. I have not checked that. Additionally, it looks like `os.Executable()` is only used on go 1.8, and I tested this on go 1.9.

**Comment by dmitshur** [comment]
I see, thanks for clarifying.

> Additionally, it looks like os.Executable() is only used on go 1.8, and I tested this on go 1.9.

I believe it's used on 1.8 and newer versions. What makes you say it's 1.8 only? If you're looking at this line:

https://github.com/kardianos/osext/blob/ae77be60afb1dcacde03767a8c37337fad28ac14/osext_go18.go#L1

The `go1.8` build constraint is satisfied by Go versions 1.8 and all newer ones, not just 1.8.

**Comment by decathorpe** [comment]
Okay, I didn't know that. I'm not familiar with how the build constraints work. Thank you for clarifying.

**Comment by anthonyfok** [comment]
See also https://bugs.debian.org/902467
