### ISSUE TITLE
osext.Executable() works differently on Windows/MacOS

### ISSUE THREAD

**Issue by tehsphinx** [kardianos/osext#28]
On MacOS when I call `osext.Executable()` I get exactly what the documentation promises:

> Executable returns an absolute path that can be used to re-invoke the current program

On Windows however I only get the name of the executable file (no path).

**Comment by kardianos** [comment]
What is your windows version and Go version you are using?

**Comment by tehsphinx** [comment]
Just checked again and it seems to work properly now. (go 1.11.1)

Before it was pretty obvious from the code that osext.Executable ran on windows that it was only returning the name of the executable file.

What version of go I had in January? Can't be sure but whatever was the latest probably.

Guess we can close this then.
