### ISSUE TITLE
string returned from Executable() may be decorated

### ISSUE THREAD

**Issue by jdef** [kardianos/osext#3]
To reproduce:
- build the binary, e.g. "km"
- start a process running "km" with some args
- delete the "km" binary
- re-build the "km" binary
- signal the already-running "km" process to spawn a child "km" process using osext.Executable() to determine the path to the binary
- OBSERVE: Executable() returns "km (deleted)" instead of "km"

``` shell
$ uname -a
Linux development-3273-e3e 3.16-0.bpo.2-amd64 #1 SMP Debian 3.16.3-2~bpo70+1 (2014-09-21) x86_64 GNU/Linux
```

**Comment by kardianos** [comment]
Fixed in https://github.com/kardianos/osext/commit/e61421bbfae9c64ff5836c1776b58b2deb34269f
