### ISSUE TITLE
Error File

### ISSUE THREAD

**Issue by nicolasStevenin** [kardianos/osext#30]
Hi,

When I test your project, I have this error :

 **command: go test -buildmode pie -compiler gc -ldflags "-X github.com/kardianos/osext/version.commit=ae77be60afb1dcacde03767a8c37337fad28ac14 -X github.com/kardianos/osext/version=0 -extldflags '-Wl,-z,relro  '"**
   testing: github.com/kardianos/osext
github.com/kardianos/osext
--- FAIL: TestExecutableDelete (0.00s)

osext_test.go:135: Child returned "/tmp/go-build341623932/b001/osext.test (deleted)", not the same file as "/tmp/go-build341623932/b001/osext.test"

Thanks

**Comment by kardianos** [comment]
What is your go version? If you are using a newer version of Go, we just call os.Executable.

**Comment by kardianos** [comment]
Timed out.
