### ISSUE TITLE
sporadic travis ci failure

### ISSUE THREAD

**Issue by daaku** [kardianos/osext#4]
Just saw this sporadic failure: https://travis-ci.org/daaku/rell/builds/57893018

```
--- FAIL: TestExecutableDelete-2 (0.08s)
    osext_test.go:109: Child returned " (deleted)/tmp/go-build754787391/github.com/daaku/rell/internal/github.com/kardianos/osext/_test/osext.test", want an absolute path
FAIL
FAIL    github.com/daaku/rell/internal/github.com/kardianos/osext   0.116s
```

Looks like the `(deleted)` is throwing it off?

**Comment by kardianos** [comment]
This is fixed on master. Pull latest.

**Comment by daaku** [comment]
It seems like on travis this is a prefix rather than a suffix the recent fix handles. I just got this failure: https://travis-ci.org/daaku/rell/builds/57896967 which is with rev 12bbb45594404d9e98107529973664c095b09add in my repo and has the fixed version: https://github.com/daaku/rell/blob/12bbb45594404d9e98107529973664c095b09add/internal/github.com/kardianos/osext/osext_procfs.go.

**Comment by kardianos** [comment]
Huh. Your analysis looks sound to me. I'll put in a prefix check as well.

**Comment by kardianos** [comment]
I've just pushed a change. Can you check if this fixes it?

**Comment by daaku** [comment]
That fixed it: https://travis-ci.org/daaku/rell/builds/57903653 -- thank you!
