### ISSUE TITLE
plans to submit to golang?

### ISSUE THREAD

**Issue by progrium** [kardianos/osext#5]
Not much in this package and seems reasonably likely to get into golang. Have you tried?

**Comment by kardianos** [comment]
It was considered a number of point versions ago. I don't recall the exact reason it wasn't included at the time.

If you'd like to, you could document the public uses of this package and suggest it for go1.6. If you do you could link it back to this issue. It is too late for go1.5; the freeze will start soon and the core team are busy. The added API would be limited to "Executable".

**Comment by kardianos** [comment]
Probably won't happen. Ref:
https://go-review.googlesource.com/#/c/16551
