### ISSUE TITLE
Windows method is slightly wrong

### ISSUE THREAD

**Issue by stevenh** [kardianos/osext#6]
The return from GetModuleFileName is not a size on all windows versions, its more success of failure indicator.

``` go
func getModuleFileName() (string, error) {
    b := make([]uint16, syscall.MAX_PATH)
    r0, _, e1 := getModuleFileNameProc.Call(0, uintptr(unsafe.Pointer(&b[0])), uintptr(uint32(len(b))))
    if r0 == 0 {
        return "", e1
    }

    return syscall.UTF16ToString(b), nil
}
```

**Comment by kardianos** [comment]
@stevenh I don't think what you suggested is correct. In my reading of
https://msdn.microsoft.com/en-us/library/windows/desktop/ms683197(v=vs.85).aspx
the current code is correct.

Can you reproduce a failure, or a fail to catch a failure? If so, let me know how to repo; I've got old version of windows around so I could test.

**Comment by kardianos** [comment]
@stevenh Without a test case I can confirm or continuing activity on this thread, I'm closing for now. I can reopen if you can give me a test case.
