### ISSUE TITLE
Copyright Information Inaccurate (?)

### ISSUE THREAD

**Issue by BenTheElder** [kardianos/osext#7]
Currently all copyright/license information says:
 `Copyright (c) 2012 The Go Authors. All rights reserved.`
You may want to update the year(s) and author(s).

As an aside: Thanks for this library! I've found it pretty handy.

**Comment by kardianos** [comment]
The year was the original year written. It should stay as is per file.

This was originally a change submitted to Go mainline, but was rejected. I've retained the copyright notice from that time. I don't have a legal department to review, but that is my view so I will leave as-is for now.

Thanks for the note.
