### ISSUE TITLE
Difference between osext and a simpler solution?

### ISSUE THREAD

**Issue by dmitshur** [kardianos/osext#9]
Hi,

I have a question about this package. I see it has a lot of internal code for each platform that performs low level operations to find out the executable name.

Can you please explain in what situations the output of `osext.Executable()` would differ from doing a much simpler operation to find out the executable path, by accessing `os.Args[0]`? Why should users use `osext.Executable()` instead of `os.Args[0]`? I'd like to understand this better.

Thank you!

**Comment by kardianos** [comment]
Hi @shurcooL ,

If you want the Executable path you can't rely on os.Args[0]. That is just the method it was called. You can call it from a relative path and not get the full path at all.

**Comment by dmitshur** [comment]
Is it impossible to resolve the relative path to absolute using [`filepath.Abs`](https://godoc.org/path/filepath#Abs)?

**Comment by kardianos** [comment]
You are suggesting WD + arg[0] = executable path. I has been a few years (2011 I think) so I don't remember the motivating example on Linux, but on Windows a windows service will have a WD of C:\windows\system32 and arg[0] will be "exec.exe", which won't pan out if you join them.

The short and long, yes, that often works. But always? No. I'm fairly sure this is true on all platforms.

**Comment by dmitshur** [comment]
I see, thank you for the answer.

**Comment by dmitshur** [comment]
> I don't remember the motivating example on Linux

If you (or anyone else) can think of one, I think it'd be great to add to README. It could be a section that explains why a naive solution may fail, and motivate the need for this library.

I personally like to understand precisely the tools I'm using, so it helps a lot to know the failure cases and concrete and reproducible reasons to pick a more complicated solution over a simpler one. Thanks again!

**Comment by kardianos** [comment]
On linux running bash compile the following program:

```
package main

import (
    "fmt"
    "os"
    "path/filepath"

    "github.com/kardianos/osext"
)

func main() {
    wd, err := os.Getwd()
    if err != nil {
        panic(err)
    }
    actual, err := osext.Executable()
    if err != nil {
        panic(err)
    }
    abs, err := filepath.Abs(os.Args[0])
    if err != nil {
        panic(err)
    }
    fmt.Printf("Arg[0]:\t\t%s\nWD:\t\t%s\nABS(arg[0]):\t%s\nActual:\t\t%s\n",
        os.Args[0],
        wd,
        abs,
        actual,
    )
}
```

then run it in bash with something like this: exec -a foo ./test1
My output is:

```
Arg[0]:     foo
WD:     /home/daniel/src/test1
ABS(arg[0]):    /home/daniel/src/test1/foo
Actual:     /home/daniel/src/test1/test1
```

Granted, this is a contrived example. Again, normally ABS(arg[0]) gives the correct answer. But if you need the correct solution always, you can't rely on arg[0]. Args can be completely faked and controlled, including the first one.

If memory serves I ran into a non-contrived situation on Linux as well where this was an issue. But memory fails me so I'll just point to the technical attributes where arg[0] can be incorrect.

**Comment by dmitshur** [comment]
That's absolutely perfect and answers my question. I am completely okay with a contrived example - any case where `os.Args[0]` may fail makes it unsuitable for the task.

Thanks, I appreciate it. I do think it'd be worth making a note of this in the README to better communicate (to other people) why this package is useful.

**Comment by dmitshur** [comment]
I see you've done exactly that in 6e7f843663477789fac7c02def0d0909e969b4e5. :) Thanks!
